[FEATURE] MichalW RestaurantDetailViewModel
Reservant-inc/reservant-mobile pull request #105
Opened 2024-05-27 10:52 UTC by skrapi2011

+ Added ViewModel
+ Some variables still needs to be added (for example reviews, menu positions, events)
+ [BUG] Mentioned in #103 still exists (branch is based on this PR)

2024-05-27 10:52 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RestaurantViewmodel](https://trello.com/c/A3t86Flg/124-restaurantviewmodel)

2024-05-27 13:56 UTC, Bambi54 requested changes

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +    val errorMessage = restaurantDetailVM.errorMessage
te zmienne niepotrzebne, możemy poprostu z vm wyciągać dane

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                CircularProgressIndicator(modifier = Modifier.align(Alignment.CenterHorizontally))
kółeczko wyświetla się w lewym górnym rogu zamiast na środku
![image](https://github.com/Reservant-inc/reservant-mobile/assets/108064906/71367888-cfa6-4c45-baca-42692a0cb047)

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +            }
error message nie pokazuje się gdy nie ma połączenia z internetem

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +    val restaurantDetailVM: RestaurantDetailViewModel = viewModel()
moim zdaniem do konstruktora vm powinniśmy przekazać restaurant id

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +    }
restaurantId do konstruktora vm, wtedy loadRestaurant możemy wywołać w bloku init

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                    text = errorMessage ?: "Unknown error",
"Elvis operator (?:) always returns the left operand of non-nullable type String?"

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                restaurant?.let { restaurant ->
"Unnecessary safe call on a non-null receiver of type RestaurantDTO?"

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                                tint = if (isFavorite) secondaryLight else Color.Gray
nie podajemy sztywno kolorów np. *secondaryLight* tylko MaterialTheme.colorscheme.secondary

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                                tint = if (isFavorite) secondaryLight else Color.Gray
nie deklarujemy też na "sztywno" kolorów tak jak po else - Color.Gray. Logika tutaj jest taka, że jeśli jest favourite to podajemy secondary kolor, a jeśli nie to ten co jest default. Wystarczy najechać myszką na tint i podpowiada co tam jest defaultowo wsadzane - LocalContentColor.current

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                        text = stringResource(R.string.label_delivery_cost) + " 5,70zł",
brakuje dwukropka, powinno być ": 5,70zł"

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                            }
to powinien być oddzielny komponen w Components, bo tego użyjemy też np. przy galerii itp

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                                    color = Color.White,
kolory nie na sztywno: color = MaterialTheme.colorScheme.onPrimaryContainer powinno być w tym przypadku

2024-05-27 13:56 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
> +            restaurant = restaurantService.getRestaurant(id).value
przydałoby się sprawdzić czy getRestaurants.isError i dopiero value przypisywać do restauracji

2024-05-27 14:40 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                                tint = if (isFavorite) secondaryLight else Color.Gray
Poprawione

2024-05-27 14:43 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                            }
Wydzielone do ImageCard

2024-05-27 14:44 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                                    color = Color.White,
Poprawione

2024-05-27 14:47 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
> +            restaurant = restaurantService.getRestaurant(id).value
Dodane

2024-05-27 15:20 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +            }
Poprawione

2024-05-27 15:20 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                CircularProgressIndicator(modifier = Modifier.align(Alignment.CenterHorizontally))
Poprawione

2024-05-28 10:35 UTC, Mroxny approved these changes

2024-05-28 16:22 UTC, Bambi54 requested changes

2024-05-28 16:22 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                        text = restaurantDetailVM.errorMessage ?: "Unknown error",
myślę że zamiast tego błędu możemy coś "przyjemniejszego" wyświetlać np. "Sorry! something went wrong"

2024-05-28 16:22 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
> +                    errorMessage = "Error while loading restaurant: ${response.errors}"
te errorsy zamiast do errormessage to trzeba wyciągnąć błędy z kluczem "TOAST" i je w error toascie wyświetlić

2024-05-28 16:24 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +                        text = restaurantDetailVM.errorMessage ?: "Unknown error",
Zmienione

2024-05-28 17:18 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantDetailViewModel.kt
> +                    errorMessage = "Error while loading restaurant: ${response.errors}"
Toast dodany

2024-05-28 20:28 UTC, Bambi54 approved these changes

2024-05-28 20:31 UTC, merged