[FIX] 2nd step verification
Reservant-inc/reservant-mobile pull request #110
Opened 2024-05-27 22:29 UTC by Dzwiedzi

potrzebujemy końcówki w backu tak jak z 1st step verification?

2024-05-28 10:22 UTC, Mroxny approved these changes

2024-05-28 16:34 UTC, Bambi54 requested changes

2024-05-28 16:34 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +        return false
raczej true

2024-05-28 16:34 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
>      fun validateSecondStep(context: Context): Boolean {
suspend

2024-05-28 16:34 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
brakuje wysłania plików i sprawdzenia informacji zwrotnej z backendu

2024-06-02 17:09 UTC, Bambi54 requested changes
1. wysyłają się requesty gdy nie ma żadnego pliku podanego
2. brakuje ikony ładowania na przycisku register po kliknięciu
3. brakuje toasta z błędem

2024-06-04 23:51 UTC, Dzwiedzi commented
Wydaje mi się że ten toast nie pasuje skoro i tak na czerwono nam świeci że plik jest nieprawidłowy to dodatkowo toast to raczej za dużo informacji o tym samym

2024-06-06 15:54 UTC, Bambi54 commented
> Wydaje mi się że ten toast nie pasuje skoro i tak na czerwono nam świeci że plik jest nieprawidłowy to dodatkowo toast to raczej za dużo informacji o tym samym

tak, toast się pojawia wtedy gdy przyjdzie z serwisu informacja że np brak połączenia

2024-06-06 16:00 UTC, Bambi54 requested changes
1. brakuje informacji że plik jest za duży
2. w logcacie sypie wyjątkami, dlaczego? java.io.FileNotFoundException: No content provider: a843a5e1-b0ce-4b68-a012-a45997bb12d3.pdf

2024-06-08 16:23 UTC, merged