Employee and MenuItem
Reservant-inc/reservant-mobile pull request #112
Opened 2024-05-28 19:55 UTC by Dzwiedzi

Wydaje mi się, że GET
/menu-items/{itemId} powinno zwracać photofillename które jest potrzebne do edycji

2024-05-28 20:44 UTC, Bambi54 requested changes
![image](https://github.com/Reservant-inc/reservant-mobile/assets/108064906/fa643d28-7870-410d-a198-3056ef03e624)
^ do poprawy

2024-05-28 20:44 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
> -                EmployeeCard(
w employeecard brakuje countdown popupa przy usuwaniu

2024-05-29 09:20 UTC, Mroxny approved these changes

2024-05-31 09:51 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/MenuItemManagementViewModel.kt
> +    }
Nie kompiluje się

2024-06-06 16:06 UTC, Bambi54 requested changes
1. przy kliknięciu add employee wpisują się dane
2. przy kliknięciu edit pola się od razu podświetlają na czerwono jako niepoprawne
3. do zrobienia rebase, michał zmienił mocno menu item komponent więc trzeba to będzie tutaj wkomponować

2024-06-17 16:37 UTC, Bambi54 requested changes
spoko, popraw tylko regex do imienia (pozwala na spacje) i regex to telefonu (możliwy numer kierunkowy)

2024-06-18 16:10 UTC, merged