[FEATURE] menu frontend validation
Reservant-inc/reservant-mobile pull request #125
Opened 2024-06-18 20:15 UTC by Bambi54

also:

- refactored file functions

2024-06-18 20:15 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [walidacja frontendowa menu](https://trello.com/c/2rLhbWj0/153-walidacja-frontendowa-menu)

2024-06-22 17:19 UTC, Mroxny requested changes

2024-06-22 17:19 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/utils/FileUtils.kt
> +}
W teorii chyba lepiej już użyć regexa bo fromString będzie czasami też parsować błędny UUID (np "1-1-1-1-1") i mu się to uda ("00000001-0001-0001-0001-000000000001")

2024-06-22 17:19 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    isAltNameInvalid: Boolean = false,
Nie lepiej przenieść ten MenuPopup do Activity? W sumie to ten komponent chyba nie będzie używany gdzie indziej

2024-06-23 13:03 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/utils/FileUtils.kt
> +}
nie wiem, ja tylko przeniosłem tą metodę z innego miejsca

2024-06-23 13:04 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    isAltNameInvalid: Boolean = false,
wydaje mi się że lepiej że to ten komponent odpowiada za wyświetlanie menupopup gdy się kliknie edit

2024-06-24 15:24 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [combobox w menu](https://trello.com/c/37ejfdbq/160-combobox-w-menu)

2024-06-25 09:33 UTC, Mroxny approved these changes

2024-06-25 09:33 UTC, merged