[FEATURE] MichalW RestaurantDetailActivity
Reservant-inc/reservant-mobile pull request #126
Opened 2024-06-21 18:59 UTC by skrapi2011

[WORK IN PROGRESS]

- Added back button in RestaurantDetailActivity

2024-06-22 13:01 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [restaurant detail acitivty](https://trello.com/c/NXtmI35m/127-restaurant-detail-acitivty)

2024-06-22 13:01 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ikonka cofnięcia w detalu restauracji](https://trello.com/c/M466TvpS/152-ikonka-cofni%C4%99cia-w-detalu-restauracji)

2024-06-23 13:13 UTC, Bambi54 requested changes
przyciski na górze do zmiany między na miejscu, dostawą można zrobić tym tab switchem, wtedy też gestami będzie można zmieniać się między ekranami

nie jestem też przekonany czy alert dialog to jest dobry pomysł, czy nie powinien być taki drawer który się wysuwa

2024-06-23 13:15 UTC, skrapi2011 commented
> przyciski na górze do zmiany między na miejscu, dostawą można zrobić tym tab switchem, wtedy też gestami będzie można zmieniać się między ekranami
> 
> nie jestem też przekonany czy alert dialog to jest dobry pomysł, czy nie powinien być taki drawer który się wysuwa

Próbowałem tym FloatinTabSwitchem, ale formatowanie sie waliło (tak jak poprzednio z Menu, lista menu wpadała pod tego FloatingTabSwitch, w tym przypadku problem rowniez istnial i nie wiedzialem jak go rozwiazac)

2024-06-26 15:49 UTC, Bambi54 requested changes

2024-06-27 13:51 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantDetailActivity.kt
> +fun SearchBarWithFilter() {
poszło

2024-06-27 14:24 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +            Button(onClick = { /* TODO: Decrease seats */ }, shape = CircleShape) {
Dodany komponent LabelButton w b07eab9e6c269ea2124b3a46afad2b61ee9ec2de

2024-06-27 14:33 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmienione

2024-06-27 14:51 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(8.dp))
Zmienione

2024-06-27 14:51 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
>                          Spacer(modifier = Modifier.width(8.dp))
Zmienione

2024-06-27 14:51 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmienione

2024-06-27 14:52 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmienione

2024-06-27 14:52 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmienione

2024-06-27 14:53 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                            Spacer(modifier = Modifier.width(8.dp))
Zmienione

2024-06-27 17:46 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        )
Dodane

2024-06-27 17:47 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmieniony

2024-06-27 17:47 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Spacer(modifier = Modifier.height(16.dp))
Zmieniony

2024-06-27 18:08 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                            ) {
Poprawione

2024-06-27 18:13 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        MyDatePickerDialog(
Zmienione

2024-06-27 19:36 UTC, Bambi54 approved these changes

2024-06-27 19:36 UTC, merged