Validation
Reservant-inc/reservant-mobile pull request #14
Opened 2024-03-17 12:23 UTC by skrapi2011

Validation of
- signInValidation()
- registerValidation()

2024-03-17 14:17 UTC, Mroxny approved these changes

2024-03-17 15:46 UTC, Bambi54 requested changes
chyba brakuje tej walidacji

2024-03-17 20:18 UTC, Mroxny approved these changes

2024-03-17 20:18 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> +    private val passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
W niedalekiej przyszłości te regexy wpisane na sztywno pewnie będą odwoływać się do resources

2024-03-17 20:38 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> +    private val passwordRegex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
Tak tak, jak będzie resources gotowe to przeniose

2024-03-18 17:43 UTC, Bambi54 approved these changes
register validation ok

2024-03-18 17:43 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> -    val emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"
mail nie powinien móc się zaczynać od + _ - lub .

2024-03-18 17:44 UTC, merged