[FEATURE] MichalW ProfileActivity
Reservant-inc/reservant-mobile pull request #146
Opened 2024-07-26 11:24 UTC by skrapi2011

- Added ProfileActivity
- Added ProfileActivityViewModel
- Added LoggedUserDTO
- Added getUser() in Service returning LoggedUserDTO
- [!] Fixed #134

2024-07-26 11:25 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ProfileActivity](https://trello.com/c/aDPLMu6O/157-profileactivity)

2024-07-27 09:53 UTC, Bambi54 requested changes
ogólnie bardzo dobrze. do zrobienia:
- resource
- informacja na ekranie gdy nie załaduje się profil

zobacz też moją drobną zmianę w vm. to całe factory trzeba pisać tylk owtedy, gdy musimy przekazać jakiś parametr do konstruktora, a tutaj jest default value, więc nie trzeba

2024-07-27 09:58 UTC, Bambi54 commented
jeśli user będzie null, to raczej traktujemy jako błąd, chyba nie może być sytuacji że przyjdzie z backendu puste 200, więc spokojnie możesz wyświetlić ten nasz komponent z "failed to load the resource" czy jakoś tak

2024-08-03 10:54 UTC, Bambi54 requested changes

2024-08-03 10:54 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                title = { Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Text(text = "Mój profil", fontWeight = FontWeight.Bold) } },
text = "Mój profil" do resource

2024-08-03 10:54 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                    profileViewModel.user.let { user ->
tu nie trzeba let, linijke wyżej jest sprawdzenie że user nie jest null więc spokojnie jeśli kompilator dalej krzyczy można user!!

2024-08-03 10:54 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                            if (user != null) {
tu to samo, w tym miejscu jesteśmy tylko wtedy gdy user != null

2024-08-03 10:54 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                            "Friends" to { FriendsTab() },
nazwy tych zakładek wrzuciłbym do resource

2024-08-20 09:47 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                title = { Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Text(text = "Mój profil", fontWeight = FontWeight.Bold) } },
Zmienione

2024-08-20 09:52 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                    profileViewModel.user.let { user ->
Zmienione

2024-08-20 09:57 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                            "Friends" to { FriendsTab() },
Dodane

2024-08-20 17:06 UTC, Bambi54 approved these changes

2024-08-20 17:09 UTC, merged