Added Birth selection and prefix selection
Reservant-inc/reservant-mobile pull request #15
Opened 2024-03-17 23:48 UTC by Dzwiedzi

2024-03-18 17:39 UTC, Bambi54 requested changes

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +        Row (Modifier.fillMaxWidth()) {
cały row do pliku components i zrób go jako birthdayInput

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +                itemsList = (1900..LocalDate.now().year-18).map { it.toString() },
odwrotnie liste, czyli od 2006 do 1900

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +                itemsList = (1..12).map { it.toString() },
przydałoby się aby jeśli rok jest pusty to aby komponent był nieaktywny - nie dało się nic wpisać

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +                itemsList = (1..YearMonth.of(registerViewModel.yearOfBirth.toInt(), registerViewModel.monthOfBirth.toInt()).lengthOfMonth()).map { it.toString() },
przydałoby się aby jeśli miesiąc jest pusty to aby komponent był nieaktywny - nie dało się nic wpisać

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +        Row (Modifier.fillMaxWidth()) {
też jako oddzielny komponent

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +                itemsList = getCountryCodesWithPrefixes(),
lista alfabetycznie po krajach

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +        Row (Modifier.fillMaxWidth()) {
zrób aby prefix zajmował ok. 30/20% szerokości komponentu, a reszta phone number, i może mały padding między

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterActivity.kt
> +fun getCountryCodesWithPrefixes(): List<String> {
metoda powinna być w viewmodelu

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> -    Column {
dlaczego usuwamy column?

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Text(text = errorText)
tekst powinien być czerwony raczej

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        Text(text = errorText)
i od lewej się zaczynać nie na środku

2024-03-18 17:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                            Toast.makeText(context, item, Toast.LENGTH_SHORT).show()
toast spoko opcja, ale raczej nie skorzystamy w tym miejscu, można usunąć

2024-03-19 14:37 UTC, Mroxny submitted a review, later dismissed

2024-03-19 15:41 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> -    Column {
Jak jest w column to rozjeżdża się phoneinput bo wtedy kolumna w wierszu na drugim miejscu. A skoro w registeractivity wszystko jest w kolumnie to raczej nie ma potrzeby zamykania dodatkowo tych inputów i errorów pod spodem w dodatkową kolumnę.

2024-03-19 17:17 UTC, Bambi54 requested changes

2024-03-19 17:17 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        )
tutaj Spacer(modifier = Modifier.weight(0.01f))

2024-03-19 17:17 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    registerViewModel: RegisterViewModel,
to samo co wyżej, przekazujemy 1 zmienną string i 2 funkcje onPrefixChange i onNumberChange

2024-03-19 17:17 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                registerViewModel.prefix = "00" + value.substringAfter(" - ").trim()
po co 00?

2024-03-19 17:17 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                if (registerViewModel.yearOfBirth.isNotEmpty()) {
po to właśnie komponent ma nie być klikalny aby nie trzeba było tutaj sprawdzać czy year jest pusty

2024-03-19 17:40 UTC, Bambi54 requested changes

2024-03-19 17:40 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        DropdownMenuBox(
strasznie ta lista zamula aplikacje. myśle że lepiej zamienić to na input i walidować czy jest to poprawny numer kierunkowy

2024-03-19 23:56 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    showError: Boolean = true
bez showError w wierszu prefix plus numer telefonu pod numerem tel prubuje się tworzyć dodatkowe pole i wszystko się rozjeżdża a jak to mamy to jest tylko error z całego phoneinput

2024-03-20 00:09 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                registerViewModel.prefix = "00" + value.substringAfter(" - ").trim()
jak dzwonisz z zagranicy do Polski np. to wpisujesz numer 0048xxxxxxxxx żeby się dodzwonić, zakładając że chcemy wysłać jakiegoś sms powitalnego czy coś to chyba możemy od razu mieć to 00 skoro i tak trzeba będzie go użyć

2024-03-20 00:09 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +        DropdownMenuBox(
możemy też założyć że klient wpisze numer dobrze w jedno pole wraz z kodem kraju.

2024-03-20 08:18 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    if (isError) {
a co jesli ktoś wybierze powiedzmy sierpień i jakimś roku, a później dzień 31 i nagle zmieni miesiąc na luty?

2024-03-21 21:08 UTC, Bambi54 requested changes
zgodnie z rozmową na dc 21.03 do poprawy, wymagania na trello lub pisz na dc

2024-03-22 15:25 UTC, Bambi54 requested changes

2024-03-22 15:25 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +    val defaultDateMillis = convertDateToMillis((LocalDate.now().year - 28).toString() + "-06-15")
tą zmienną trzeba usunąć, i wszystko to co po = wrzucić bezpośrednio do initialSelectedDateMillis poniżej

2024-03-22 15:51 UTC, Bambi54 submitted a review, later dismissed

2024-03-22 15:55 UTC, Bambi54 approved these changes

2024-03-22 16:49 UTC, Mroxny approved these changes

2024-03-22 16:50 UTC, merged