[REFACTOR] MaciekM friends service
Reservant-inc/reservant-mobile pull request #150
Opened 2024-08-05 23:29 UTC by Mroxny

Dodatkowe fixy dla sps i service util

2024-08-05 23:30 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Porządki w serwisach](https://trello.com/c/zBMW4ODB/177-porz%C4%85dki-w-serwisach)

2024-08-06 20:55 UTC, Bambi54 requested changes

2024-08-06 20:55 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/models/dtos/FriendRequestDTO.kt
> +     * Date in 'yyyy-MM-d'T'H:mm:ss.yyyy'Z'' format
te formaty napewno z ' w środku? i chyba dd i HH powinno być

2024-08-07 09:51 UTC, Bambi54 approved these changes

2024-08-07 09:51 UTC, merged