[FEATURE] Chat
Reservant-inc/reservant-mobile pull request #151
Opened 2024-08-07 21:16 UTC by Dzwiedzi

2024-08-09 11:11 UTC, Mroxny requested changes
Ekrany trochę niezgodne z tym co mamy na figmie
![image](https://github.com/user-attachments/assets/d8a12772-ed73-47b6-9128-a8727126fbb7)

2024-08-09 11:11 UTC, Mroxny commented on app/src/main/java/reservant_mobile/ui/activities/ChatListActivity.kt
> +                )
Brakuje strzałki cofającej

2024-08-11 18:07 UTC, Bambi54 requested changes
do poprawy zgodnie z review maćka. oprócz tego nie mam uwag

2024-08-15 19:07 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ChatActivity](https://trello.com/c/ZJFgvVnB/180-chatactivity)

2024-08-20 17:11 UTC, Bambi54 approved these changes
👍

2024-08-20 17:18 UTC, merged