[REFACTOR] MaciekM restaurant service
Reservant-inc/reservant-mobile pull request #159
Opened 2024-08-16 11:42 UTC by Mroxny

good luck :>

2024-08-16 11:49 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Porządki w serwisach](https://trello.com/c/zBMW4ODB/177-porz%C4%85dki-w-serwisach)

2024-08-20 17:21 UTC, Bambi54 requested changes

2024-08-20 17:21 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
> +     * Available order values : DateAsc, DateDesc, CostAsc, CostDesc
moim zdaniem tutaj tak samo jak w UserService - jakiś enum na te możliwe filtry

2024-08-20 17:21 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
> +     * Available visitSorting values : DateAsc, DateDesc
tu też

2024-08-20 17:21 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
> +     * Available order values : NameAsc, NameDesc, AmountAsc, AmountDesc
tu też

2024-08-20 17:21 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/RestaurantService.kt
> +     * Available order values : OrderTimeAsc, OrderTimeDesc, DeliveredTimeAsc, DeliveredTimeDesc
tu też

2024-08-26 20:02 UTC, merged

2024-08-26 20:02 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [enumy w serwisach](https://trello.com/c/3nCEKSwR/188-enumy-w-serwisach)