[REFACTOR] MaciekM users
Reservant-inc/reservant-mobile pull request #161
Opened 2024-08-19 21:54 UTC by Mroxny

2024-08-19 21:55 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor users service](https://trello.com/c/1p3Bmygz/186-refactor-users-service)

2024-08-20 17:02 UTC, Bambi54 requested changes

2024-08-20 17:02 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/UserService.kt
> +     * Available filter values : NoFilter, FriendsOnly, StrangersOnly
skoro tylko 3 wartości dozwolone ja bym to enumem zrobił..

2024-08-20 17:02 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/data/services/UserService.kt
> +                filter = filter,
.. i tutaj jakąś metodę tostring z tego enuma

2024-08-26 19:36 UTC, merged

2024-08-26 20:02 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [enumy w serwisach](https://trello.com/c/3nCEKSwR/188-enumy-w-serwisach)