[REFACTOR] MichałW RestaurantDetail refactor
Reservant-inc/reservant-mobile pull request #163
Opened 2024-08-26 09:35 UTC by skrapi2011

+ Moved reservation to new activity
+ Added support for backend photos (restaurantDetail main photo, menuItems photos)

2024-08-26 09:42 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [przeniesienie rezerwacji do nowego activity](https://trello.com/c/LeAljSJP/170-przeniesienie-rezerwacji-do-nowego-activity)

2024-08-26 20:02 UTC, Bambi54 requested changes
drobne poprawki, ale poza tym elegancko zrobione, zdjęcia działają także jest git :)

2024-08-26 20:02 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/RestaurantReservationActivity.kt
> +                }
ten tekst nagłówka jest rozjechany na górze, myślę że jeśli wywalisz navigationIcon i zrobisz "ręcznie" ikonę w samym topBarze to uda się wycentrować wszystko

2024-08-27 14:47 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/RestaurantReservationActivity.kt
> +                        .padding(start = 16.dp, end = 16.dp, bottom = 8.dp)
Poprawione

2024-08-31 09:15 UTC, Bambi54 approved these changes

2024-08-31 09:15 UTC, merged