[FEATURE] MichalW Other users
Reservant-inc/reservant-mobile pull request #164
Opened 2024-08-26 10:56 UTC by skrapi2011

+ Refactored ProfileActivity to fit other users (add friend, send message, removed edit profile)
[!] Hardcoded - Endpoint missing in backend for fetching other users simple info (name, birthdate etc)

2024-08-26 10:56 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [rozbudowa ProfileActivity o innych użytkowników](https://trello.com/c/hNdUsgEJ/179-rozbudowa-profileactivity-o-innych-u%C5%BCytkownik%C3%B3w)

2024-08-26 10:56 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [rozbudowa ProfileActivity o innych użytkowników](https://trello.com/c/hNdUsgEJ/179-rozbudowa-profileactivity-o-innych-u%C5%BCytkownik%C3%B3w)

2024-08-26 20:08 UTC, Bambi54 requested changes

2024-08-26 20:08 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
>                              Row(
tutaj kolumna a nie row

2024-08-26 20:08 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                                    Text(text = stringResource(R.string.label_send_message))
brakuje jakiś drobnych ikonek, analogicznie jak na figmie

2024-08-26 20:08 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                    FloatingTabSwitch(pages = listOf(
floating tab switcha nie powinno być jeśli profil jkest innego usera. wtedy wyświetlamy tylko eventsy

2024-08-27 13:26 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
>                              Row(
Zmienione

2024-08-27 14:08 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                                    Text(text = stringResource(R.string.label_send_message))
Dodane

2024-08-27 14:32 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                    FloatingTabSwitch(pages = listOf(
Zmienione

2024-08-31 09:18 UTC, Bambi54 approved these changes

2024-08-31 09:18 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ProfileActivity.kt
> +                            EventsContent() // TODO: better events component
ten komponent będzie do naprawy, tam jest spacer na 64.dp którego nie powinno być

2024-08-31 09:19 UTC, merged