[FIX] authorId
Reservant-inc/reservant-mobile pull request #170
Opened 2024-09-03 20:14 UTC by Dzwiedzi

2024-09-05 09:21 UTC, Mroxny requested changes

2024-09-05 09:21 UTC, Mroxny commented on app/src/main/java/reservant_mobile/ui/viewmodels/ChatViewModel.kt
> +    }
Info o obecnym użytkowniku lepiej pobrać z `UserService.UserObject.userId`, ponieważ `getUserInfo()` wysyła request do backendu. UserObject to singleton który lokalnie przechowuje dane obcenie zalogowanego użytkownika

2024-09-05 09:21 UTC, Mroxny commented on app/src/main/java/reservant_mobile/ui/viewmodels/ChatViewModel.kt
> +                // You can handle errors here, such as displaying a toast or logging
Tutaj (i w innych miejscach) nie powinny już być te errory obsłużone?

2024-09-06 17:39 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/viewmodels/ChatViewModel.kt
> +                // You can handle errors here, such as displaying a toast or logging
w vm nie trzeba obsługiwać błędów, wystarczy się upewnić że w activity się nic nie wywali później

2024-09-14 09:37 UTC, Bambi54 requested changes

2024-09-14 09:37 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ChatActivity.kt
> +                    keyboardOptions = KeyboardOptions.Default.copy(imeAction = ImeAction.None) // Disable send on enter
chodziło o wyłączenie tej opcji tylko wtedy gdy nie są załadowane dane, standardowo powinna zostać

2024-09-14 09:38 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/ChatActivity.kt
> +                    keyboardOptions = KeyboardOptions.Default.copy(imeAction = ImeAction.None) // Disable send on enter
i zrób rebase pls

2024-09-24 15:59 UTC, merged