[FEATURE] MaciekM map search filters
Reservant-inc/reservant-mobile pull request #184
Opened 2024-09-30 08:45 UTC by Mroxny

* search filters
* user location

2024-09-30 08:47 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [wyszukiwanie i filtry restauracji z mapy](https://trello.com/c/5GKWSDfU/212-wyszukiwanie-i-filtry-restauracji-z-mapy)

2024-09-30 08:47 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pobieranie lokalizacji użytkownika](https://trello.com/c/tsvw91HM/213-pobieranie-lokalizacji-u%C5%BCytkownika)

2024-10-01 18:32 UTC, Bambi54 requested changes
wizualnie fajnie, podoba mi się. problem z funkcjonalnością:

- jeśli ustawimy filtr na np. 2 gwiazdki, to wyszuka się, ale jak potem z powrotem na 5 to dostaję timeout i "could not find resource"
- podobnie jak wejdę w którąś restaurację a potem wrócę do tego ekranu
- filtr też nie działa jeśli wybierzemy takie dane dla których nie ma żadnej restauracji (np. 1 gwiazdka i jakieś 4 tagi)

przy okazji eventy też nie działają

2024-10-02 12:45 UTC, Mroxny commented
> * jeśli ustawimy filtr na np. 2 gwiazdki, to wyszuka się, ale jak potem z powrotem na 5 to dostaję timeout i "could not find resource"


bo nie ma żadnych restauracji ktore maja 5 gwiazdek, to ze na początku jest to widac w filtrach to niedopatrzenie z mojej strony

2024-10-02 12:47 UTC, Mroxny commented
> * filtr też nie działa jeśli wybierzemy takie dane dla których nie ma żadnej restauracji (np. 1 gwiazdka i jakieś 4 tagi)

could not find resource oznacza ze nie znaleziono restauracji

2024-10-02 13:03 UTC, Mroxny commented
> przy okazji eventy też nie działają

a tutaj nie mam bladego pojecia dlaczego, dane normalnie sie pobieraja i parsuja ale z jakiegos powodu nie wstawiają się do widoku 🥲

2024-10-07 10:21 UTC, Mroxny commented
Dobra naprawione to ładowanie, wystarczyo użyć loadState...

2024-10-07 10:22 UTC, Mroxny commented
Ale tych eventów to wciąż się nie udału i tutaj autentycznie nie mam pomysłu dlaczego. To jest to samo co przy pobieraniu restauracji a i tak nie działa...

2024-10-07 11:33 UTC, Bambi54 commented
> Ale tych eventów to wciąż się nie udału i tutaj autentycznie nie mam pomysłu dlaczego. To jest to samo co przy pobieraniu restauracji a i tak nie działa...
> 
> Postaram się tym zając jeszcze w tym tygodniu ale tymczasowo mozna mergować

dobra, jeszcze zerkne po pracy na kod i zobacze czy cos wpadnie

2024-10-08 06:35 UTC, merged