[FEATURE] Social tab
Reservant-inc/reservant-mobile pull request #187
Opened 2024-10-08 20:18 UTC by Bambi54

- refactored all settings navigation
- changed profilevm loading logic
- removed unnecessary settings
- added social tab
- moved orders to settings

2024-10-08 20:24 UTC, Bambi54 commented
![](https://github.trello.services/images/mini-trello-icon.png) [zakładka społeczność](https://trello.com/c/RQqkztot/215-zak%C5%82adka-spo%C5%82eczno%C5%9B%C4%87)

2024-10-09 12:54 UTC, Mroxny requested changes

2024-10-09 12:54 UTC, Mroxny commented on app/src/main/java/reservant_mobile/ui/activities/ChatListActivity.kt
> +                    onReturnClick = { navController.navigate(MainRoutes.Settings) } //TODO zmienic w przyszłości
Wywala *Destination with route Settings cannot be found in navigation graph*

2024-10-09 12:55 UTC, Mroxny commented
![image](https://github.com/user-attachments/assets/b162c744-3909-4fc4-b1c5-b316e6185e1d)

imo tutaj zdj profilowe powinno być okrągłe trochę jak tutaj 
![image](https://www.designyourway.net/diverse/6/uilist/2555750.jpg)

2024-10-12 13:14 UTC, merged