[FEATURE] MichalW Profile refactor
Reservant-inc/reservant-mobile pull request #189
Opened 2024-10-12 15:20 UTC by skrapi2011

+ Added star next to rating
+ Removed Send Message text
+ Refactored Add Friend text - now it changes to Cancel after sending friend request
+ Removed searchbar
+ Fixed Events
+ Changed header to IconWithHeader
+ Added optional action button in IconWithHeader

2024-10-12 15:20 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [refactor profilu](https://trello.com/c/xFfuxF4C/219-refactor-profilu)

2024-10-13 09:52 UTC, Bambi54 requested changes
tekst rating do wyrzucenia moim zdaniem:
![image](https://github.com/user-attachments/assets/fe6fcc1c-1845-49c1-b96f-dccffe182cb2)

nie widzę tego przycisku do edytowania w headerze:
![image](https://github.com/user-attachments/assets/7b225fac-6dfa-49c1-8dbb-92056a5ccce5)

2024-10-13 09:52 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/viewmodels/ProfileViewModel.kt
>              if (user?.userId != profileUserId) {
bez sensu 2 razy pobierasz informację o userze, skorzystaj z UserObjecta w UserService zamiast user?.userId

2024-10-14 14:21 UTC, Bambi54 approved these changes

2024-10-14 14:21 UTC, merged