[FEATURE] MichalW Add Event Activity
Reservant-inc/reservant-mobile pull request #192
Opened 2024-10-14 20:44 UTC by skrapi2011

Added event add activity:
![image](https://github.com/user-attachments/assets/1526ad78-f69a-4d5d-8685-ed7de6ecba15)
![image](https://github.com/user-attachments/assets/084e795c-aa0b-4fa1-bb20-47c3058b4465)

2024-10-15 11:51 UTC, Mroxny approved these changes
Ok, tylko zerknij na konflikty

2024-10-15 17:03 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [ekran dodawania eventów i przycisk do nawigacji](https://trello.com/c/08kRamQl/184-ekran-dodawania-event%C3%B3w-i-przycisk-do-nawigacji)

2024-10-15 18:12 UTC, Bambi54 requested changes
- do dodania date picker z wyborem godziny
- zmienić funkcję `MyDatePicker` żeby przyjmowała `label:String` zamiast funkcji composable
- dodanie walidacji pól

2024-11-03 14:14 UTC, Bambi54 requested changes

2024-11-03 14:14 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/AddEventActivity.kt
> +    LazyColumn(
zmienić na zwykłe Column zamiast Lazy

2024-11-03 14:14 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/AddEventActivity.kt
> +                        MyTimePickerDialog(
dziwnie się focusuje ten komponent, zmień aby focus requester nie był w środku komponentu tworzony. co jeśli go wyrzucimy?

2024-11-03 14:14 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/AddEventActivity.kt
> +                LazyColumn(
![image](https://github.com/user-attachments/assets/1119f8fe-7ceb-4b7f-be00-b3120035f9bc)
coś się dziwnie ładuje ten komponent kiedy search jest pusty

2024-11-03 14:14 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/viewmodels/AddEventViewModel.kt
> +class AddEventViewModel(
ja bym zmienił na poprostu `EventViewModel` bo użyjemy go też do detalu

2024-11-04 15:32 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/AddEventActivity.kt
> +    LazyColumn(
Zmienione

2024-11-04 16:29 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/activities/AddEventActivity.kt
> +                LazyColumn(
Zmienione - CircularProgressIndicator podczas wczytywania restauracji, gdy lista jest pusta to tekst że jest pusta

2024-11-04 16:31 UTC, skrapi2011 commented on app/src/main/java/reservant_mobile/ui/viewmodels/AddEventViewModel.kt
> +class AddEventViewModel(
Już na [feature-MichalW-EventDetail](https://github.com/Reservant-inc/reservant-mobile/tree/feature-MichalW-EventDetail) jest inny viewModel przygotowany pod detal :/

2024-11-05 20:54 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/viewmodels/AddEventViewModel.kt
> +class AddEventViewModel(
ale właśnie to powinien być moim zdaniem ten sam vm tu i tu

2024-11-08 21:24 UTC, Bambi54 requested changes
poprawki zgodnie z info na zajęciach

2024-11-12 17:45 UTC, Bambi54 requested changes
walidacja backendowa i walidacja na zdjęcie (nie może być puste, musi być zdjęcie, max rozmiar)

poza tym git

2024-11-17 12:10 UTC, closed without merging

2024-11-17 12:11 UTC, skrapi2011 commented
Zamykam ze względu na przeniesienie na [nowy PR](https://github.com/Reservant-inc/reservant-mobile/pull/244)