[FEATURE] Order summary for employee
Reservant-inc/reservant-mobile pull request #204
Opened 2024-10-23 01:41 UTC by Dzwiedzi

2024-10-23 08:49 UTC, Mroxny approved these changes

2024-10-29 12:17 UTC, Bambi54 requested changes
1. coś nie tak z end time: 
![image](https://github.com/user-attachments/assets/78e07fcb-834a-4a85-adf6-e2df814e6be1)
2. format daty w date i payment time zmień na dd.MM.yyyy HH:mm
![image](https://github.com/user-attachments/assets/71608273-adf1-408c-ae29-8dd24e9d653f)
3. order id nie wyświetlamy użytkownikowi
4. total cost jest 2x, ja bym zostawił ten w komponencie orders
5. jeżeli któreś pole jest null lub unkown to moimi zdaniem całego komponentu nie pokazujmy
6. tip nie ma waluty

2024-10-29 12:17 UTC, Bambi54 commented on app/src/main/java/reservant_mobile/ui/activities/OrderDetailsScreen.kt
> +    }
do zastąpienia przez `LoadingScreenWithTimeout`

2024-10-31 20:34 UTC, Bambi54 requested changes
do dodania poprawki o których mówiliśmy na zajęciach
- wygląd pozycji w zamówieniu
- poprawa ceny pozycji (obecnie jest ilość x total)

2024-11-06 12:21 UTC, Dzwiedzi commented
Błagam merge

2024-11-07 22:00 UTC, merged