[FEATURE] Tables
Reservant-inc/reservant-mobile pull request #220
Opened 2024-10-28 23:19 UTC by Dzwiedzi

2024-10-29 12:19 UTC, Bambi54 requested changes
ja bym to zrobił tak jak jest ten ekran główny, czyli takie bardziej kafelki ze zdjęciem stolika "w tle"

dodaj jeszcze status, narazie zhardcodowany, z jakimiś kolorami, czyli jak wolne to na zielono, jak zajęte to żółty

2024-10-29 12:31 UTC, Dzwiedzi commented
> ja bym to zrobił tak jak jest ten ekran główny, czyli takie bardziej kafelki ze zdjęciem stolika "w tle"
> 
> dodaj jeszcze status, narazie zhardcodowany, z jakimiś kolorami, czyli jak wolne to na zielono, jak zajęte to żółty

no teraz ten kolor w tle komponentu jest statusem jest zahardcodowane że dostępny i dlatego wszystkie są na zielono

2024-10-29 20:21 UTC, Bambi54 commented
usunięcie "ID" z komponentu

2024-10-30 02:14 UTC, Dzwiedzi commented
![obraz](https://github.com/user-attachments/assets/69dc892b-7c4f-4434-98a0-950023399823)

2024-11-03 14:15 UTC, Bambi54 requested changes
ostatnie co to dodałbyś aby w tle tej karty było zdjęcie stołu, coś podobnego jak jest w `EmployeeHomeActivity`

2024-11-05 20:51 UTC, Bambi54 approved these changes

2024-11-08 21:29 UTC, Bambi54 requested changes
do naprawy, pojawił się problem z resource'ami

2024-11-12 17:48 UTC, Bambi54 approved these changes
będzie kilka zmian w tym ekranie, ale narazie ok, merguje

2024-11-12 17:56 UTC, merged