Wysyłanie oraz odbiór odpowiedzi logowania poprzez userService
Reservant-inc/reservant-mobile pull request #23
Opened 2024-03-22 13:20 UTC by skrapi2011

2024-03-22 16:04 UTC, Bambi54 requested changes

2024-03-22 16:04 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +    fun login(): Boolean{
to musi być suspend fun

2024-03-22 16:04 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            viewModelScope.launch {
bez tej korutyny, ją zrobimy w activity

2024-03-22 16:04 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
> +        UserButton(onClick = { print("LOGIN-API RESPONSE: ${loginViewModel.login()}\n") }, label = "login")
tutaj w onClick odpalamy korutyne. loginViewModel.viewModelScope.launch i w środku nasza funkcja login

2024-03-22 16:17 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/LoginActivity.kt
> +        UserButton(onClick = { print("LOGIN-API RESPONSE: ${loginViewModel.login()}\n") }, label = "login")
Dobra, pozniej doślę

2024-03-22 16:26 UTC, Mroxny requested changes

2024-03-22 16:26 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +    fun login(): Boolean{
ta funkcja tak naprawdę powinna po prostu zwalidować lokalne dane i jeżeli wszystko jest ok to zwraca wynik z funkcji logującej w UserService.

2024-03-23 17:13 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            // TODO: loading screen, 3 different responses instead true/false
A skąd loginActivity ma wiedzieć że false który dostał od login() oznacza złe dane logowania a nie błąd w połączeniu z serwerem?

2024-03-23 18:52 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            // TODO: loading screen, 3 different responses instead true/false
jest napisane w todo ze to do zmiany jest potem na uzycie resources, tylko ze nie jest jeszcze to zaimplementowane

2024-03-23 21:44 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            // TODO: loading screen, 3 different responses instead true/false
aa ok ok my bad, źle przeczytałem

2024-03-23 23:45 UTC, Mroxny approved these changes

2024-03-24 11:53 UTC, Bambi54 approved these changes

2024-03-24 11:54 UTC, Mroxny approved these changes

2024-03-24 11:54 UTC, merged