[FEATURE] warehouse
Reservant-inc/reservant-mobile pull request #240
Opened 2024-11-13 02:52 UTC by Dzwiedzi

2024-11-15 17:49 UTC, Bambi54 requested changes
- zmiana nazwy stock na warehouse na głównym ekranie
- ilość w koszyku jako bubble, analogicznie jak na ekranie zamawiania (nowy komponent do tego i podmienić tu i tam)
- edycja ilości składnika w magazynie i informacji o składniku (wszystkie pola jako disabled jeśli zalogowany user to pracownik)

2024-11-17 01:09 UTC, Dzwiedzi commented
Nie wiem które pola tutaj wyłączyć bo aktualnie pracownik ale tylko zaplecza może edytować składnik(nazwa itp) ale nie może go dodać więc musimy to ustalić które pola wyłączamy i czy tylko dla dodawania czy też dla edycji

2024-11-17 10:23 UTC, Bambi54 requested changes
1. edycja składnika powinna być disabled dla pracownika - możliwość tylko zmiany obecnej ilości wraz z notatką
2. Koszyk - przycisk do usuwania po prawej stronie
3. Usunąłbym tekst "Name: xxx" i zostawił samą nazwę składnika na górze karty. wydaje się oczywiste że to jest nazwa

poza tym elegancko zrobione

2024-11-17 10:24 UTC, Bambi54 commented
> Nie wiem które pola tutaj wyłączyć bo aktualnie pracownik ale tylko zaplecza może edytować składnik(nazwa itp) ale nie może go dodać więc musimy to ustalić które pola wyłączamy i czy tylko dla dodawania czy też dla edycji

moim zdaniem powinno być wszystko wyłączone i dać możliwość dodawania i edycji składników tylko dla ownera

2024-11-17 15:26 UTC, Bambi54 approved these changes

2024-11-17 17:47 UTC, merged