[FEATURE] ingerdient history
Reservant-inc/reservant-mobile pull request #252
Opened 2024-11-27 16:10 UTC by Dzwiedzi

2024-11-30 17:57 UTC, Bambi54 requested changes
dodaj jeszcze tylko sprawdzenie, żeby hall employee nie widział przycisku warehouse w home

2024-11-30 17:58 UTC, Bambi54 commented
i konflikty

2024-12-12 22:00 UTC, Bambi54 requested changes
konflikty i czekamy na rozwiązanie maćka w kwestii paginacji na ingredients

2024-12-13 09:03 UTC, Mroxny commented
#276

2024-12-13 09:08 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [rozwiązanie problemu paginacji ingredients](https://trello.com/c/a8f22be9/277-rozwi%C4%85zanie-problemu-paginacji-ingredients)

2024-12-18 09:43 UTC, merged