[REFACTOR] api service
Reservant-inc/reservant-mobile pull request #30
Opened 2024-04-02 21:06 UTC by Mroxny

2024-04-06 19:45 UTC, Bambi54 requested changes

2024-04-06 19:45 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/services/APIService.kt
>          install(HttpCookies)
cookies chyba nie potrzebne juz?

2024-04-06 19:45 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/services/LocalBearerService.kt
> +            ""
tu chyba jakaś obsługa błędu by się przydała

2024-04-06 19:45 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
> +    const val LOGIN="/auth/login"
czemu endpointy bez {BACKEND_URL} na początku?

2024-04-07 09:46 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/APIService.kt
>          install(HttpCookies)
Zostawiłbym na wszelki wypadek. W kontekście działania aplikaci i wydajności nic to nie zmienia. Jedyna zmiana to że aplikacja będzie zajmować kilka kb miejsca więcej

2024-04-07 09:48 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/LocalBearerService.kt
> +            ""
Odniosłem się do tego wyżej
> Muszę jeszcze zamienić `first()[bearerTokenKey].toString()` na `first()[bearerTokenKey].toString().orEmpty()`

2024-04-07 09:51 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/constants/Endpoints.kt
> +    const val LOGIN="/auth/login"
Ustawiłem w ApiService domyślny url. Teraz wystarczy do kazdego requesta dodawać tylko końcówki 
```kotlin
defaultRequest {
            url(Endpoints.BACKEND_URL)
```

2024-04-07 10:04 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/LocalBearerService.kt
> +            ""
Chodzi o to że że ta funkcja nie może zwracać nulla ponieważ potem wartość tej funkcji ląduje bezpośrednio w parametrze zapytania. DataStore zwraca string albo null w zależności czy znajdzie wartość do podanego klucza

2024-04-08 18:39 UTC, merged