Dev feature kacper n home screen
Reservant-inc/reservant-mobile pull request #31
Opened 2024-04-04 11:27 UTC by Dzwiedzi

2024-04-06 19:48 UTC, Bambi54 requested changes
jest ok, tylko home niech zostanie taki jaki był, zrób oddzielną aktywność 'LandingPageActivity' do której będziemy wpadać po zalogowaniu się i tam ten scaffold i navbar itp.

2024-04-07 19:08 UTC, Mroxny submitted a review, later dismissed
Jest ok ale ja bym zostawił sam haburger, bez paska z tytułem
![Bez tytułu](https://github.com/Reservant-inc/reservant-mobile/assets/50219282/7caad19c-125a-4ba1-97ba-ad164e0fc7ea)

2024-04-09 09:09 UTC, Mroxny submitted a review, later dismissed

2024-04-09 15:28 UTC, Bambi54 approved these changes

2024-04-09 15:31 UTC, Mroxny approved these changes

2024-04-09 15:40 UTC, merged