[FEATURE] RegisterRestaurantActivity
Reservant-inc/reservant-mobile pull request #32
Opened 2024-04-07 16:04 UTC by skrapi2011

Added: 
- RegisterRestaurantActivity
- RestaurantTypeDropdown Composable
- InputUserFile Composable

BUG:
- Clicking on RestaurantTypeDropdown textArea not showing menu, only arrow works

2024-04-07 16:05 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RegisterRestaurantActivity](https://trello.com/c/ATxbcJWP/41-registerrestaurantactivity)

2024-04-07 19:33 UTC, Mroxny requested changes

2024-04-07 19:33 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                    contentDescription = if (expanded) "Zwiń" else "Rozwiń"
Olek coś wspominał że content description też miał się odwolywać do resource

2024-04-08 08:38 UTC, Mroxny requested changes

2024-04-08 08:38 UTC, Mroxny commented on app/src/androidTest/java/com/example/reservant_mobile/RegisterRestaurantActivityTest.kt
> +        rule.onNodeWithText("Name").performTextInput("Test name")
Przy stringach powinniśmy odwoływać się do resource

2024-04-08 08:38 UTC, Mroxny commented on app/src/androidTest/java/com/example/reservant_mobile/RegisterRestaurantActivityTest.kt
> +        ).assertExists()
Napierw klikasz w przycisk a potem sprawdzasz czy istnieje XD

2024-04-09 15:56 UTC, Mroxny approved these changes

2024-04-09 16:04 UTC, Mroxny approved these changes

2024-04-09 16:05 UTC, merged