added Toast
Reservant-inc/reservant-mobile pull request #37
Opened 2024-04-13 21:37 UTC by Dzwiedzi

2024-04-13 22:15 UTC, Mroxny approved these changes

2024-04-14 12:39 UTC, Bambi54 requested changes
kolor errora powinien być czerwony

2024-04-14 13:30 UTC, Mroxny commented
@Bambi54 
> kolor errora powinien być czerwony

Nawet jeżeli da się zrobić żeby toast wyświetlał tekst w innym kolorze to not sure czy to dobry pomysł bo to po prostu wygląda nienaturalnie. Z reguły toasty w androidzie mają jeden predefiniowany styl

![image](https://github.com/Reservant-inc/reservant-mobile/assets/50219282/f9824df1-0e35-4d71-a71b-b9e56f4222de)
![image](https://github.com/Reservant-inc/reservant-mobile/assets/50219282/531b96f2-cbb1-4273-8b25-2d37a0f810a4)

2024-04-14 13:32 UTC, Bambi54 commented
nie kolor toasta tylko tekstu na nim na czerwono żeby wyglądało że jest błąd

2024-04-14 13:34 UTC, Mroxny commented
No rozumiem ale szczerze to nie spotkałem się chyba nigdy z innym kolorem tekstu niż standardowy

2024-04-14 22:39 UTC, Dzwiedzi commented
Mi się wydaje, że powinniśmy to zostawić tak jak jest. Fakt że coś ci wyskakuje chyba jest dostateczną informacją o błędzie.

2024-04-15 16:21 UTC, Bambi54 approved these changes

2024-04-16 15:04 UTC, Mroxny approved these changes

2024-04-16 15:05 UTC, merged