Updated ViewModel
Reservant-inc/reservant-mobile pull request #44
Opened 2024-04-16 22:13 UTC by Dzwiedzi

2024-04-17 10:39 UTC, Bambi54 requested changes

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
> +    suspend fun registerRestaurant(restaurant: RestaurantDTO): Result<Boolean> {
dlaczego restaurant zamiast registerrestaurant?

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    var description by mutableStateOf("")
tego typu pola będą do zmiany na FormField. pokażę w jaki sposób to implementować

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
>      suspend fun registerRestaurant(context: Context): Int {
Boolean zwracany, nie int

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
>              return R.string.error_register_invalid_request
nie zwracamy już id resource'ów tylko boolean czy zarejestrowany czy nie

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
>          val rService = RestaurantService()
serwis inicjalizujemy w konstruktorze viewmodelu

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +        val fDto: FileUploadDTO? = file?.let { FileUploadService().sendFile(type, it).value }
fileuploadservice też w konstruktorze inicjalizacja

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> -                isValidUri(consentUri) ||
dlaczego nie ma walidacji??

2024-04-17 10:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +        return uri == null
potrzebujemy sprawdzic jesli nie jest nullem to czy jest to poprawny uri

2024-04-17 10:42 UTC, Bambi54 commented
brakuje też testów, mówiłem żeby chociaż proste zacząć robić

2024-04-17 11:49 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
> +    suspend fun registerRestaurant(restaurant: RestaurantDTO): Result<Boolean> {
to akurat była moja sugestia. RegisterRestaurant wprowadza zbędną redundancję. RestaurantDTO jest obiektem, który powinien w pełni pokryć nasze potrzeby (zwłaszcza, że prawdopodobnie będzie uzywany dosyc często) a rrDTO ostateznie różnił sie chyba bodajrze jednym polem (id).

2024-04-23 15:25 UTC, Bambi54 requested changes

2024-04-23 15:25 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/models/dtos/RegisterRestaurantDTO.kt
> +    val logo: String
zrób rebase bo konflikty będą, te rzeczy w dto już są na mainie

2024-04-23 15:25 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    suspend fun registerRestaurant(context: Context): Boolean {
brakuje funkcji validateFirstStep i validateFiles

2024-04-23 15:25 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    var delivery by mutableStateOf(true)
raczej false z defaulta

2024-04-26 10:06 UTC, Bambi54 requested changes
ogólnie jest ok. brakuje analogicznych suspend funkcji i walidacji do 2 kroku "pliki"

2024-04-26 10:06 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/utils/GetFlieNameUtil.kt
> +package com.example.reservant_mobile.data.utils
nazwa pliku "File" zamiast "Flie"

2024-04-26 10:06 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    var result by mutableStateOf(Result(isError = false, value = false))
moim zdaniem 3 odzielne resulty na każdy wynik danego kroku

2024-04-26 10:06 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +//                areTagsInvalid()
czemu wykomentowane?

2024-04-26 10:06 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    fun isRestaurantRegistrationInvalid(context: Context): Boolean {
git że wszystko sprawdzane, podoba mi się

2024-04-26 10:33 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +//                areTagsInvalid()
Wydaje mi się, że tagi mogą być puste

2024-04-27 16:52 UTC, Bambi54 approved these changes

2024-04-27 16:52 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterRestaurantViewModel.kt
> +    var result3 by mutableStateOf(Result(isError = false, value = false))
jakieś lepsze nazwy następnym razem

2024-04-28 10:25 UTC, Mroxny approved these changes

2024-04-28 10:25 UTC, merged