[REFACTOR] [FIXED] RestaurantManageActivity + RestaurantViewModel
Reservant-inc/reservant-mobile pull request #52
Opened 2024-04-21 10:53 UTC by skrapi2011

+ Added viewModel with basic functions
+ Refactored RestaurantManagement:
![image](https://github.com/Reservant-inc/reservant-mobile/assets/91696484/8121dff3-2047-4412-84e6-87d82e179721)

2024-04-21 10:53 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RestaurantManagementViewmodel](https://trello.com/c/GEoCXTu0/48-restaurantmanagementviewmodel)

2024-04-21 10:54 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RestaurantManagementActivity](https://trello.com/c/vvftw3Px/54-restaurantmanagementactivity)

2024-04-21 11:01 UTC, Mroxny approved these changes

2024-04-22 16:24 UTC, Bambi54 requested changes
w jaki sposób mogę to odpalić / przetestować / zobaczyć? przy preview dostaję błąd że "failed to instantiate viewmodel"

2024-04-22 16:24 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RestaurantManagementViewModel.kt
> +        viewModelScope.launch {
viewmodel odpalamy w activity, nie w viewmodelu

2024-04-22 20:39 UTC, Bambi54 requested changes
jeśli nie ma żadnych tagów to nie wyświetlajmy pustego komponentu.
myślę że te trzy kropeczki powinny być w tej karcie która się wyświetla, np prawy dolny róg

2024-04-23 12:43 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
>  fun RestaurantManagementActivity(navController: NavHostController) {
Update: topbar usuniety wraz ze Scaffoldem

2024-04-23 15:19 UTC, Bambi54 requested changes
dla restauracji: "a", "Miriam Staśkiewicz", "Kuba Biliński" rzuca wyjątkami:
HttpClient: RESPONSE http://172.21.40.127:12038/my-restaurants/6 failed with exception: io.ktor.serialization.JsonConvertException: Illegal input: Unexpected JSON token at offset 203: Unexpected 'null' value instead of string literal at path: $.rentalContract

 HttpClient: RESPONSE http://172.21.40.127:12038/my-restaurants/3 failed with exception: io.ktor.serialization.JsonConvertException: Illegal input: Unexpected JSON token at offset 244: Unexpected 'null' value instead of string literal at path: $.alcoholLicense

popraw dto żeby były nulle dozwolone, usuń restaurantManagement z maina i loginu i będzie do merge

2024-04-23 15:20 UTC, Bambi54 requested changes

2024-04-23 15:20 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/models/dtos/RestaurantDTO.kt
> +    val tags:List<String>,
dlaczego tagi i description zmienione?

2024-04-23 20:46 UTC, Bambi54 approved these changes

2024-04-23 21:15 UTC, Mroxny approved these changes

2024-04-23 21:15 UTC, merged