[FEATURE] EmployeeManagement
Reservant-inc/reservant-mobile pull request #55
Opened 2024-04-24 12:32 UTC by Dzwiedzi

2024-04-27 15:30 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
> +                EmployeeManagementActivity()
nie wiem czy specjalnie ale brakuje `import EmployeeManagementActivity`

2024-04-27 15:30 UTC, Mroxny approved these changes

2024-04-30 09:37 UTC, Bambi54 requested changes
do zrobienia rebase, w RestaurantEmployee lista ról do zmiany z list<string> na list<roles>

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
> +fun EmployeeManagementActivity() {
zarządzamy pracownikami w obrębie danej restauracji, więc raczej musimy do konstruktora activity przekazać restaurantId i potem je w konstruktorze viewmodelu przekazać

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +    var isLoading by mutableStateOf(true)
mutablestateod(false) raczej

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +    private fun fetchEmployees() {
zrób tą funkcję jako suspend, a korutyne uruchamiaj w inicie

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                text = "Login: ${employee.login}",
te wszystkie opisy z resource'ów musimy pobierać żeby było tłumaczenie

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +            HorizontalDivider(thickness = 1.dp, color = Color.Gray)
ogólnie jest git, ale to tego typu rzeczy używamy koloru MaterialTheme.colorScheme.outline, aby w dark modzie też dobrze wyglądało

2024-04-30 09:37 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +class EmployeeViewModel(private val restaurantService: IRestaurantService = RestaurantService()) : ViewModel() {
brakuje metody do dodania pracownika i do edytowania danych

2024-04-30 21:28 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +class EmployeeViewModel(private val restaurantService: IRestaurantService = RestaurantService()) : ViewModel() {
Wydaje mi się, że nie mamy opcji edytowania pracownika. Dodawanie już jest

2024-05-05 11:15 UTC, Bambi54 requested changes

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
> +    val employeeViewModel = EmployeeViewModel(restaurantId)
nie tworzymy tak viewmodelu, tylko viewModel<EmployeeViewModel>()

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +    var hasError by mutableStateOf(false)
dlaczego hasError jest oddzielnie od resulta? nie możesz skorzystać z isError w Resulcie?

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/HomeActivity.kt
> +                EmployeeManagementActivity(1)
do zrobienia rebase i nawigacja do tego activity. na mainie jest zmergowane RestaurantManagement i tam w momencie klinięcia manageEmployee przechodzimy do tego activity

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/EmployeeManagementViewModel.kt
> +    var employees by mutableStateOf<List<RestaurantEmployeeDTO>>(emptyList())
nawet jeśli api nie zwraca żadnych danych, to zamiast emptyList zrób chociaż kilku employees, żeby coś zobaczyć na ekranie

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
> +            Button(
ten button jakiś ciekawszy można zrobić, nie taki jak mamy dosłownie wszędzie. np zamiast button możesz użyć card, zrobić je szare z plusem na środku i dodać modifier.clickable()

2024-05-05 11:15 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +fun AddEmployeeDialog(onDismiss: () -> Unit, vm: EmployeeViewModel) {
fajny komponent

2024-05-05 17:55 UTC, Dzwiedzi commented on app/src/main/java/com/example/reservant_mobile/ui/activities/EmployeeManagementActivity.kt
> +    val employeeViewModel = EmployeeViewModel(restaurantId)
Próbowałem, nie mam pojęcia jak użyć viewModel(), jeśli chcemy przekazać jakiś argument

2024-05-06 19:59 UTC, Bambi54 requested changes
ogólnie ok, ale do poprawy jest komponent employee. przydałyby się dwukropki po login i phone oraz inne wyświetlanie booleanów z hall i backdoor employee. zmieniłem też jedną linię kodu którą poprawiłem też w innym commicie

2024-05-07 15:56 UTC, Bambi54 approved these changes

2024-05-07 19:14 UTC, Mroxny approved these changes

2024-05-07 19:14 UTC, merged