[FEATURE] RestaurantManagementActivity group support
Reservant-inc/reservant-mobile pull request #57
Opened 2024-04-25 15:10 UTC by skrapi2011

- Activity now displays restaurants depending on a selected group
- If user has only 1 group, there will be no option for choosing a group
![image](https://github.com/Reservant-inc/reservant-mobile/assets/91696484/20bca563-1232-4941-a0fc-22c0a18aa72b)

2024-04-27 15:38 UTC, Mroxny approved these changes

2024-04-27 17:02 UTC, Bambi54 requested changes

2024-04-27 17:02 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RestaurantManagementActivity.kt
> +    NavHost(navController = navController, startDestination = RestaurantManagementRoutes.ACTIVITY_MANAGE) {
navhost z 1 composable w środku nam niepotrzebny

2024-04-27 17:03 UTC, Bambi54 approved these changes

2024-04-28 10:27 UTC, Mroxny approved these changes

2024-04-28 11:57 UTC, Mroxny approved these changes

2024-04-29 15:48 UTC, Bambi54 approved these changes

2024-04-29 15:48 UTC, merged