[REFACTOR] MaciekM api service
Reservant-inc/reservant-mobile pull request #66
Opened 2024-05-06 19:31 UTC by Mroxny

* RestaurantService
* RestaurantMenuSeervice

2024-05-06 19:40 UTC, Mroxny commented
![](https://github.trello.services/images/mini-trello-icon.png) [Restaurant & Menu service](https://trello.com/c/uxaRk934/92-restaurant-menu-service)

2024-05-06 20:02 UTC, Bambi54 requested changes

2024-05-06 20:02 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantMenuService.kt
>  interface IRestaurantMenuService{
brakuje delete menu

2024-05-06 20:02 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
> +    suspend fun deleteEmployment(id: Any): Result<Boolean>
fireEmployee() prędzej niż deleteEmployment

2024-05-06 22:17 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantMenuService.kt
>  interface IRestaurantMenuService{
fakt, nie ma w swaggerze i o tym zapomniałem

2024-05-06 22:21 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/data/services/RestaurantService.kt
> +    suspend fun deleteEmployment(id: Any): Result<Boolean>
pomijając fakt małej istotności takiej zmiany to myślę że lepiej posługiwać się technicznym językiem przy takich rzeczach. Programistom może być łatwej wyszukać nazwy, która nazywa się "delete..." gdy chcą się czegoś pozbyć. Z technicznego punktu widzenia zatrudnienie zostaje usunięte.

2024-05-07 15:57 UTC, Bambi54 approved these changes

2024-05-07 15:57 UTC, merged