Login and Register ViewModels
Reservant-inc/reservant-mobile pull request #8
Opened 2024-03-11 19:22 UTC by skrapi2011

Added:
- RegisterViewModel

2024-03-11 19:30 UTC, Bambi54 commented
zmiana funkcji walidujących na 1 funkcję validateWithRegex

2024-03-11 19:31 UTC, Bambi54 requested changes

2024-03-11 19:31 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> +
zmiana funkcji walidujących na 1 funkcję validateWithRegex

2024-03-11 19:58 UTC, Bambi54 requested changes

2024-03-11 19:58 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            isValid.value = login.isNotBlank() && password.isNotBlank()
rozdziel sprawdzanie na oddzielne funkcje

2024-03-11 20:53 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> +
Zmienione

2024-03-11 20:53 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/LoginViewModel.kt
> +            isValid.value = login.isNotBlank() && password.isNotBlank()
Rozdzielone na validateLogin i validatePassword

2024-03-11 20:57 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RegisterViewModel](https://trello.com/c/Gu0I7o9C/5-registerviewmodel)

2024-03-11 20:57 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [LoginViewModel](https://trello.com/c/TYuOhpso/6-loginviewmodel)

2024-03-12 12:24 UTC, skrapi2011 commented on app/src/main/java/com/example/reservant_mobile/ui/viewmodels/RegisterViewModel.kt
> +    fun validateForm(registerUserDTO: RegisterUserDTO) {
Dodane

2024-03-12 12:39 UTC, Mroxny approved these changes

2024-03-12 18:58 UTC, Bambi54 approved these changes

2024-03-12 18:58 UTC, merged