[FIX] tag selection and choosing new group
Reservant-inc/reservant-mobile pull request #87
Opened 2024-05-19 12:57 UTC by Dzwiedzi

2024-05-19 16:42 UTC, Bambi54 requested changes

2024-05-19 16:42 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
> +                                .padding(horizontal = 12.dp, vertical = 6.dp)
jako oddzielny komponent

2024-05-19 16:42 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/activities/RegisterRestaurantActivity.kt
> +                        label = stringResource(R.string.label_add_to_group)
grupy będą do zmieny zgodnie z rozmową

2024-05-21 15:02 UTC, Bambi54 approved these changes

2024-05-21 17:59 UTC, Mroxny approved these changes

2024-05-21 17:59 UTC, merged