[REFACTOR] Navigation bar
Reservant-inc/reservant-mobile pull request #88
Opened 2024-05-19 13:49 UTC by Dzwiedzi

2024-05-21 12:20 UTC, Mroxny commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                selected = item.route.toString().replace("$", ".").split("@")[0] == currentRoute,
wydaje mi sie że są juz gotowe metody sprawdzania rodzaju obiektu

2024-05-21 14:39 UTC, Bambi54 requested changes

2024-05-21 14:39 UTC, Bambi54 commented on app/src/main/java/com/example/reservant_mobile/ui/components/Components.kt
> +                selected = item.route.toString().replace("$", ".").split("@")[0] == currentRoute,
co tutaj się dzieje? dlaczego w ten sposób sprawdzamy te routy?

2024-05-21 20:19 UTC, Bambi54 requested changes
do zmiany zgodnie z informacją na discordzie:
"myślę że najlepiej byłoby poprostu przechowywać obecnie kliknięty item
jako state
i przy kliku jeśli jest inny no to nawigować a jak nie to nic nie robić"

2024-05-22 07:19 UTC, Bambi54 approved these changes

2024-05-22 07:19 UTC, merged