[FEATURE] RestaurantDetailActivity
Reservant-inc/reservant-mobile pull request #92
Opened 2024-05-19 15:56 UTC by skrapi2011

![image](https://github.com/Reservant-inc/reservant-mobile/assets/91696484/cec90327-1358-4946-abd4-99e2a9efe6f5)

2024-05-19 15:57 UTC, skrapi2011 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RestaurantDetail](https://trello.com/c/TzWBEuyb/101-restaurantdetail)

2024-05-19 16:27 UTC, Bambi54 requested changes
- dodanie half star
- przeniesienie komponentów do components.kt

2024-05-19 16:52 UTC, Bambi54 commented
zmiana galerii na coś podobnego do: https://m3.material.io/components/carousel/overview

2024-05-20 11:04 UTC, Mroxny approved these changes

2024-05-21 14:51 UTC, Bambi54 requested changes
zgodnie z informacją na dc:
"dobra mysle ze najlepiej bedzie te image wrzucic w card, dac 0 albo 4dp padding w srodku i dodac elevation
i jest szansa ze bedzie wygladalo podobnie"

2024-05-21 19:43 UTC, Mroxny approved these changes

2024-05-21 19:43 UTC, merged